### PR TITLE
assignment one

### PR DESCRIPTION
**Pull request by devangi-hub**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Assignment-1.sql and er diagram
## What did you learn from the changes you have made?
SQL query syntaxes
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
For queries, they are written while doing assignment
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
no
## How were these changes tested?
locally 
## Checklist
- [ X ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by efantinatti — CHANGES_REQUESTED** [review]
Dear Devangi Vyas

Session 1:
1 - OK.

Session 2:
2 - WHERE: Q2 - option 1 and 2: The query intepretation is different from what os being asked. Please review te question.

Session 3:
3 - AGGREGATE: Q2 - Please review your query. Not following the question requirements.
4 - Temp Table: - Please review it. Answer is not what is being asked.

Final:
4 - Please review it prior merging your feature branch 'assignment-one' to 'main'.

Mark: 24 points.

**Comment by devangi-hub** [comment]
Dear @efantinatti Sir,

Can you please review this updated pull request.

Thank you

**Comment by efantinatti** [comment]
All good @devangi-hub. You can merge it into `main` accordingly.

**Comment by devangi-hub** [comment]
merging with main branch

**Pull request merged**
